[project]
name = "codementor"
version = "0.1.0"
description = "An interactive programming learning platform"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.32.0",
    "pandas>=2.2.0",
    "numpy>=1.26.3",
    "autopep8>=2.3.2",
    "js>=1.0",
    "beautifier>=0.5.5",
    "black>=25.1.0",
    "plotly>=6.0.1",
    "jsbeautifier>=1.15.4",
    "pyperclip>=1.8.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/codementor"] 
