[litellm]
OPENROUTER_API_KEY = "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"
LITELLM_MODEL_NAME = "openai/gpt-3.5-turbo"
LITELLM_API_BASE = "https://openrouter.ai/api/v1"
MAX_TOKENS = "1000"
TEMPERATURE = "0.7" 